name: Pathways Education Services
favicon: null
layout_spectrum: 0.5371190069708973
typography_spectrum: 0.1764484904706478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8d6caf'
    - '#b7a8c5'
    - '#231f20'
    - '#555555'
  brandStrength: 0.8125
  lightness: 0.8825911290477961
  saturation: 0.06893672398291528
  rhythmicContrast: 0.5
purpose: []
